// SP テンプレ展開ビルドスクリプト
// spec: docs/decisions/0002-template-generalization.md §3.5
//
// Usage:
//   bun run scripts/build-prompt.ts                # 最新 vN を generate
//   bun run scripts/build-prompt.ts --version v2   # 明示指定
//   bun run scripts/build-prompt.ts --check        # generated と template+config 整合チェック (CI 用)

import Mustache from "mustache";
import { parse as parseYaml } from "yaml";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const CONFIG_PATH = resolve(ROOT, "instance.config.yaml");
const PROMPTS_DIR = resolve(ROOT, "worker/src/prompts");

const FOOTER_TEMPLATE = `\n\n<!-- generated by scripts/build-prompt.ts from instance.config.yaml + system-prompt.{version}.template.md, do not edit manually -->\n`;

/**
 * Render a Mustache template, throwing if any referenced variable is missing.
 *
 * Mustache.js の default は「missing variable は空文字に置換」だが、テンプレ化の事故防止のため
 * 事前に template の variable 参照を抽出して view に存在するか検証する。
 */
export function renderStrict(template: string, view: Record<string, unknown>): string {
  const tokens = Mustache.parse(template);
  const referencedPaths = collectVariablePaths(tokens);
  for (const path of referencedPaths) {
    if (!hasNestedPath(view, path)) {
      throw new Error(`Template requires '{{${path}}}' but config does not provide it`);
    }
  }
  return Mustache.render(template, view);
}

/** Walk Mustache tokens, collecting top-level variable name paths (excluding section item refs like '.'). */
function collectVariablePaths(tokens: unknown[]): string[] {
  const paths: string[] = [];
  for (const tok of tokens) {
    if (!Array.isArray(tok)) continue;
    const [type, name] = tok as [string, string, ...unknown[]];
    // type: 'name' = {{var}}, '&' = {{&var}}/{{{var}}}, '#' = {{#section}}
    // '^' (inverted section) is intentionally excluded — its purpose is to render
    // when the key is ABSENT, so requiring it would defeat the point.
    if (type === "name" || type === "&" || type === "#") {
      if (name !== ".") paths.push(name);
    }
    // Sub-tokens (index 4 in mustache.js token format) reference fields of the section's items
    // (or the parent context for ^), which we can't statically validate without rendering. Skip.
  }
  return paths;
}

function hasNestedPath(obj: unknown, path: string): boolean {
  const parts = path.split(".");
  let cur: unknown = obj;
  for (const p of parts) {
    if (cur == null || typeof cur !== "object") return false;
    if (!(p in (cur as Record<string, unknown>))) return false;
    cur = (cur as Record<string, unknown>)[p];
  }
  return true;
}

interface Args {
  version: string;
  check: boolean;
}

export function parseArgs(argv: string[]): Args {
  let version = "v2.1"; // default to latest
  let check = false;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--version") {
      const next = argv[i + 1];
      if (next !== undefined && !next.startsWith("--")) {
        version = next;
        i++;
      }
    } else if (argv[i] === "--check") {
      check = true;
    }
  }
  return { version, check };
}

function loadConfig(): Record<string, unknown> {
  const raw = readFileSync(CONFIG_PATH, "utf8");
  const config = parseYaml(raw) as Record<string, unknown>;
  // プリプロセス: テンプレが {{domains_length}} を要求するので注入
  if (Array.isArray(config.domains)) {
    config.domains_length = config.domains.length;
  }
  return config;
}

function buildOne(version: string): { templatePath: string; outputPath: string; output: string } {
  const templatePath = resolve(PROMPTS_DIR, `system-prompt.${version}.template.md`);
  const outputPath = resolve(PROMPTS_DIR, `system-prompt.${version}.md`);
  if (!existsSync(templatePath)) {
    throw new Error(`Template not found: ${templatePath}`);
  }
  const template = readFileSync(templatePath, "utf8");
  const view = loadConfig();
  const rendered = renderStrict(template, view);
  // Use the function form to avoid String.prototype.replace's $-special interpretation
  // (e.g. if version contained "$1" it would be mangled).
  const footer = FOOTER_TEMPLATE.replace("{version}", () => version);
  return { templatePath, outputPath, output: rendered + footer };
}

function main(argv: string[]) {
  const args = parseArgs(argv);
  const { outputPath, output } = buildOne(args.version);

  if (args.check) {
    const existing = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
    if (existing !== output) {
      console.error(`drift detected: ${outputPath} does not match template + config render`);
      console.error(`run 'bun run scripts/build-prompt.ts --version ${args.version}' to regenerate`);
      process.exit(1);
    }
    console.log(`ok: ${outputPath} matches template + config`);
    return;
  }

  writeFileSync(outputPath, output);
  console.log(`wrote: ${outputPath}`);
}

if (import.meta.main) {
  main(process.argv.slice(2));
}
